// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BoothsColumns holds the columns for the "booths" table.
	BoothsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "user_booth", Type: field.TypeInt, Unique: true},
	}
	// BoothsTable holds the schema information for the "booths" table.
	BoothsTable = &schema.Table{
		Name:       "booths",
		Columns:    BoothsColumns,
		PrimaryKey: []*schema.Column{BoothsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "booths_users_booth",
				Columns:    []*schema.Column{BoothsColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ChargeRequestsColumns holds the columns for the "charge_requests" table.
	ChargeRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "charge_request_user", Type: field.TypeInt},
		{Name: "user_charge_requests", Type: field.TypeInt, Nullable: true},
	}
	// ChargeRequestsTable holds the schema information for the "charge_requests" table.
	ChargeRequestsTable = &schema.Table{
		Name:       "charge_requests",
		Columns:    ChargeRequestsColumns,
		PrimaryKey: []*schema.Column{ChargeRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "charge_requests_users_user",
				Columns:    []*schema.Column{ChargeRequestsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "charge_requests_users_charge_requests",
				Columns:    []*schema.Column{ChargeRequestsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "price", Type: field.TypeInt64},
		{Name: "booth_products", Type: field.TypeInt, Nullable: true},
		{Name: "product_booth", Type: field.TypeInt},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "products_booths_products",
				Columns:    []*schema.Column{ProductsColumns[4]},
				RefColumns: []*schema.Column{BoothsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "products_booths_booth",
				Columns:    []*schema.Column{ProductsColumns[5]},
				RefColumns: []*schema.Column{BoothsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TransactionsColumns holds the columns for the "transactions" table.
	TransactionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "quantity", Type: field.TypeInt64},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeString},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "booth_transactions", Type: field.TypeInt},
		{Name: "product_transactions", Type: field.TypeInt},
		{Name: "user_transactions", Type: field.TypeInt},
	}
	// TransactionsTable holds the schema information for the "transactions" table.
	TransactionsTable = &schema.Table{
		Name:       "transactions",
		Columns:    TransactionsColumns,
		PrimaryKey: []*schema.Column{TransactionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "transactions_booths_transactions",
				Columns:    []*schema.Column{TransactionsColumns[5]},
				RefColumns: []*schema.Column{BoothsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_products_transactions",
				Columns:    []*schema.Column{TransactionsColumns[6]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "transactions_users_transactions",
				Columns:    []*schema.Column{TransactionsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "point", Type: field.TypeInt64},
		{Name: "pin", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "USER"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BoothsTable,
		ChargeRequestsTable,
		ProductsTable,
		TransactionsTable,
		UsersTable,
	}
)

func init() {
	BoothsTable.ForeignKeys[0].RefTable = UsersTable
	ChargeRequestsTable.ForeignKeys[0].RefTable = UsersTable
	ChargeRequestsTable.ForeignKeys[1].RefTable = UsersTable
	ProductsTable.ForeignKeys[0].RefTable = BoothsTable
	ProductsTable.ForeignKeys[1].RefTable = BoothsTable
	TransactionsTable.ForeignKeys[0].RefTable = BoothsTable
	TransactionsTable.ForeignKeys[1].RefTable = ProductsTable
	TransactionsTable.ForeignKeys[2].RefTable = UsersTable
}
