// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"somapay-backend/ent/booth"
	"somapay-backend/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Booth is the model entity for the Booth schema.
type Booth struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BoothQuery when eager-loading is set.
	Edges        BoothEdges `json:"edges"`
	user_booth   *int
	selectValues sql.SelectValues
}

// BoothEdges holds the relations/edges for other nodes in the graph.
type BoothEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Products holds the value of the products edge.
	Products []*Product `json:"products,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*Transaction `json:"transactions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BoothEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProductsOrErr returns the Products value or an error if the edge
// was not loaded in eager-loading.
func (e BoothEdges) ProductsOrErr() ([]*Product, error) {
	if e.loadedTypes[1] {
		return e.Products, nil
	}
	return nil, &NotLoadedError{edge: "products"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e BoothEdges) TransactionsOrErr() ([]*Transaction, error) {
	if e.loadedTypes[2] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Booth) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case booth.FieldID:
			values[i] = new(sql.NullInt64)
		case booth.FieldName:
			values[i] = new(sql.NullString)
		case booth.ForeignKeys[0]: // user_booth
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Booth fields.
func (_m *Booth) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case booth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case booth.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case booth.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_booth", value)
			} else if value.Valid {
				_m.user_booth = new(int)
				*_m.user_booth = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Booth.
// This includes values selected through modifiers, order, etc.
func (_m *Booth) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Booth entity.
func (_m *Booth) QueryUser() *UserQuery {
	return NewBoothClient(_m.config).QueryUser(_m)
}

// QueryProducts queries the "products" edge of the Booth entity.
func (_m *Booth) QueryProducts() *ProductQuery {
	return NewBoothClient(_m.config).QueryProducts(_m)
}

// QueryTransactions queries the "transactions" edge of the Booth entity.
func (_m *Booth) QueryTransactions() *TransactionQuery {
	return NewBoothClient(_m.config).QueryTransactions(_m)
}

// Update returns a builder for updating this Booth.
// Note that you need to call Booth.Unwrap() before calling this method if this Booth
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Booth) Update() *BoothUpdateOne {
	return NewBoothClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Booth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Booth) Unwrap() *Booth {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Booth is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Booth) String() string {
	var builder strings.Builder
	builder.WriteString("Booth(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Booths is a parsable slice of Booth.
type Booths []*Booth
