// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"somapay-backend/ent/chargerequest"
	"somapay-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChargeRequestDelete is the builder for deleting a ChargeRequest entity.
type ChargeRequestDelete struct {
	config
	hooks    []Hook
	mutation *ChargeRequestMutation
}

// Where appends a list predicates to the ChargeRequestDelete builder.
func (_d *ChargeRequestDelete) Where(ps ...predicate.ChargeRequest) *ChargeRequestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChargeRequestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChargeRequestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChargeRequestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chargerequest.Table, sqlgraph.NewFieldSpec(chargerequest.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChargeRequestDeleteOne is the builder for deleting a single ChargeRequest entity.
type ChargeRequestDeleteOne struct {
	_d *ChargeRequestDelete
}

// Where appends a list predicates to the ChargeRequestDelete builder.
func (_d *ChargeRequestDeleteOne) Where(ps ...predicate.ChargeRequest) *ChargeRequestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChargeRequestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chargerequest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChargeRequestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
