// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"somapay-backend/ent/chargerequest"
	"somapay-backend/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ChargeRequest is the model entity for the ChargeRequest schema.
type ChargeRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount int64 `json:"amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChargeRequestQuery when eager-loading is set.
	Edges                ChargeRequestEdges `json:"edges"`
	charge_request_user  *int
	user_charge_requests *int
	selectValues         sql.SelectValues
}

// ChargeRequestEdges holds the relations/edges for other nodes in the graph.
type ChargeRequestEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChargeRequestEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChargeRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chargerequest.FieldID, chargerequest.FieldAmount:
			values[i] = new(sql.NullInt64)
		case chargerequest.FieldStatus:
			values[i] = new(sql.NullString)
		case chargerequest.ForeignKeys[0]: // charge_request_user
			values[i] = new(sql.NullInt64)
		case chargerequest.ForeignKeys[1]: // user_charge_requests
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChargeRequest fields.
func (_m *ChargeRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chargerequest.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chargerequest.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case chargerequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case chargerequest.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field charge_request_user", value)
			} else if value.Valid {
				_m.charge_request_user = new(int)
				*_m.charge_request_user = int(value.Int64)
			}
		case chargerequest.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_charge_requests", value)
			} else if value.Valid {
				_m.user_charge_requests = new(int)
				*_m.user_charge_requests = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChargeRequest.
// This includes values selected through modifiers, order, etc.
func (_m *ChargeRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ChargeRequest entity.
func (_m *ChargeRequest) QueryUser() *UserQuery {
	return NewChargeRequestClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this ChargeRequest.
// Note that you need to call ChargeRequest.Unwrap() before calling this method if this ChargeRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChargeRequest) Update() *ChargeRequestUpdateOne {
	return NewChargeRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChargeRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChargeRequest) Unwrap() *ChargeRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChargeRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChargeRequest) String() string {
	var builder strings.Builder
	builder.WriteString("ChargeRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// ChargeRequests is a parsable slice of ChargeRequest.
type ChargeRequests []*ChargeRequest
