// Code generated by ent, DO NOT EDIT.

package ent

import (
	"somapay-backend/ent/chargerequest"
	"somapay-backend/ent/schema"
	"somapay-backend/ent/transaction"
	"somapay-backend/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chargerequestFields := schema.ChargeRequest{}.Fields()
	_ = chargerequestFields
	// chargerequestDescStatus is the schema descriptor for status field.
	chargerequestDescStatus := chargerequestFields[1].Descriptor()
	// chargerequest.DefaultStatus holds the default value on creation for the status field.
	chargerequest.DefaultStatus = chargerequestDescStatus.Default.(string)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescTimestamp is the schema descriptor for timestamp field.
	transactionDescTimestamp := transactionFields[3].Descriptor()
	// transaction.DefaultTimestamp holds the default value on creation for the timestamp field.
	transaction.DefaultTimestamp = transactionDescTimestamp.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[4].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
}
