// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldPoint holds the string denoting the point field in the database.
	FieldPoint = "point"
	// FieldPin holds the string denoting the pin field in the database.
	FieldPin = "pin"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// EdgeBooth holds the string denoting the booth edge name in mutations.
	EdgeBooth = "booth"
	// EdgeTransactions holds the string denoting the transactions edge name in mutations.
	EdgeTransactions = "transactions"
	// EdgeChargeRequests holds the string denoting the charge_requests edge name in mutations.
	EdgeChargeRequests = "charge_requests"
	// Table holds the table name of the user in the database.
	Table = "users"
	// BoothTable is the table that holds the booth relation/edge.
	BoothTable = "booths"
	// BoothInverseTable is the table name for the Booth entity.
	// It exists in this package in order to avoid circular dependency with the "booth" package.
	BoothInverseTable = "booths"
	// BoothColumn is the table column denoting the booth relation/edge.
	BoothColumn = "user_booth"
	// TransactionsTable is the table that holds the transactions relation/edge.
	TransactionsTable = "transactions"
	// TransactionsInverseTable is the table name for the Transaction entity.
	// It exists in this package in order to avoid circular dependency with the "transaction" package.
	TransactionsInverseTable = "transactions"
	// TransactionsColumn is the table column denoting the transactions relation/edge.
	TransactionsColumn = "user_transactions"
	// ChargeRequestsTable is the table that holds the charge_requests relation/edge.
	ChargeRequestsTable = "charge_requests"
	// ChargeRequestsInverseTable is the table name for the ChargeRequest entity.
	// It exists in this package in order to avoid circular dependency with the "chargerequest" package.
	ChargeRequestsInverseTable = "charge_requests"
	// ChargeRequestsColumn is the table column denoting the charge_requests relation/edge.
	ChargeRequestsColumn = "user_charge_requests"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPassword,
	FieldPoint,
	FieldPin,
	FieldRole,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByPoint orders the results by the point field.
func ByPoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoint, opts...).ToFunc()
}

// ByPin orders the results by the pin field.
func ByPin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPin, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByBoothField orders the results by booth field.
func ByBoothField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBoothStep(), sql.OrderByField(field, opts...))
	}
}

// ByTransactionsCount orders the results by transactions count.
func ByTransactionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTransactionsStep(), opts...)
	}
}

// ByTransactions orders the results by transactions terms.
func ByTransactions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTransactionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChargeRequestsCount orders the results by charge_requests count.
func ByChargeRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChargeRequestsStep(), opts...)
	}
}

// ByChargeRequests orders the results by charge_requests terms.
func ByChargeRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChargeRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBoothStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BoothInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, BoothTable, BoothColumn),
	)
}
func newTransactionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TransactionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TransactionsTable, TransactionsColumn),
	)
}
func newChargeRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChargeRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChargeRequestsTable, ChargeRequestsColumn),
	)
}
