// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Booth is the predicate function for booth builders.
type Booth func(*sql.Selector)

// ChargeRequest is the predicate function for chargerequest builders.
type ChargeRequest func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
